osx_image: xcode8
language: objective-c

script: 
- xcodebuild -sdk iphonesimulator clean
- xcodebuild -scheme Jayme -project Jayme.xcodeproj -destination 'platform=iOS Simulator,name=iPhone 7,OS=10.0' test

after_success:
  - bash <(curl -s https://codecov.io/bash)
