osx_image: xcode7.3
language: objective-c

before_install:
# - brew update || brew update
# - brew outdated xctool || brew upgrade xctool
- git clone https://github.com/facebook/xctool.git

script: 
- xctool clean build -project Jayme.xcodeproj -scheme Jayme -sdk iphonesimulator
- xcodebuild -scheme Jayme -project Jayme.xcodeproj -sdk iphonesimulator9.3 -destination 'platform=iOS Simulator,name=iPhone 6s,OS=9.3' test

after_success:
  - bash <(curl -s https://codecov.io/bash)